### ISSUE TITLE
setup Kanban board (1 point)

### ISSUE THREAD

**Issue by sediqullahbadakhsh** [sediqullahbadakhsh/recipe-app-group-project#12]
In this issue my Team  @andres-condezo  and @sediqullahbadakhsh :

- created the kanban board `https://github.com/users/sediqullahbadakhsh/projects/9`
- assigned tasks

**Comment by rloterh** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the provided link for the board is displaying as 404. Kindly ensure to provide a valid link for the board.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by sediqullahbadakhsh** [comment]
Thanks, fix it, the project was set to private, now changed it to the public, it should be visible now.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @sediqullahbadakhsh and @andres-condezo,

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
